### PR TITLE
html + css + js icons

### PR DESCRIPTION
**Pull request by germanfr**
Pushed this ones for a taste. If you like them I'll do more. Suggest any improvement please.
text-html text-css text-javascript

### CODE REVIEW

**Comment by crutchcorn** [comment]
I personally like these ones!

**Comment by dominicap** [comment]
This is how I thought they should look

html css

**Comment by danielhickman** [comment]
I really like the colored, centered ones.

**Comment by dominicap** [comment]
Well since the majority like the colored ones I guess they are the ones :)

**Pull request merged**
