### PR TITLE
Add new feature to resize tool (select type of icon)

### PR DESCRIPTION
**Pull request by germanfr**
I added a parameter to choose the destination folder (by default apps) so that it is more generic. Hope it helps :+1:

### CODE REVIEW

**Comment by crutchcorn** [comment]
I love it. However, please not that there are now 3 types of bash files. This is because of the new folder colors. Please change the name from resize.sh to brownapps.sh

**Comment by german6** [comment]
Okay I'll do it

**Comment by germanfr** [comment]
@crutchcorn done! :+1:

**Comment by deadbaed** [comment]
merge or delete?

**Pull request merged**
