### PR TITLE
Resize all svg to 192x192 under petition

### PR DESCRIPTION
**Pull request by germanfr**

### CODE REVIEW

**Comment by deadbaed** [comment]
why do you want to resize them? 48x48 is not good?
and don't use 192x192, use the biggest size supported, 256x256

**Comment by germanfr** [comment]
@loctauxphilippe I did it under petition.

**Comment by deadbaed** [comment]
@german6 which petition?

**Comment by germanfr** [comment]
@loctauxphilippe @crutchcorn asked me for it. 192x192 is a good size because edges are 1px width this way, if I'm right.

**Comment by deadbaed** [comment]
@german6 oh ok I see :)
but the problem is that the sizes for linux icons don't include 192x192.
you can have 128x128, or 256x256 (the bigger).

maybe we'll have to deal that with @crutchcorn or @danielhickman

**Comment by danielhickman** [comment]
Partial alignment is pretty bad. Either way it looks really weird. (256 or 48)

**Comment by germanfr** [comment]
What do you mean? @danielhickman

**Comment by deadbaed** [comment]
I think that we don't care about the svg sizes of the icons, because most of them are in png (except for apps)

**Comment by deadbaed** [comment]
I'm closing this, cause we won't merge it because of the wrong sizes

**Pull request closed without merging**
