### PR TITLE
Add software updates icon

### PR DESCRIPTION
**Pull request by germanfr**
system-software-update update-manager
From: [Icons to make](https://github.com/materialos/Linux-Icon-Pack/issues/32)

### CODE REVIEW

**Comment by deadbaed** [comment]
does the icon work?

**Comment by germanfr** [comment]
@loctauxphilippe Why not?

**Comment by deadbaed** [comment]
@german6 I mean, show me that it works

**Comment by germanfr** [comment]
@loctauxphilippe  I don't have that update manager installed. I have mintUpdate

**Pull request merged**
