### PR TITLE
Active and inactive bluetooth status icons

### PR DESCRIPTION
**Pull request by germanfr**
bluetooth bluetooth

bluetooth-disabled bluetooth-disabled

### CODE REVIEW

**Comment by crutchcorn** [comment]
Can you confirm that this actually works?

**Comment by germanfr** [comment]
Those icons come with the gnome pack. What do you mean with "work"?

**Comment by crutchcorn** [comment]
I am just checking that these icons actually apply properly

**Comment by germanfr** [comment]
I don't know. Im just theming the icons I see on the gnome theme and placing them in the same folder with the same name. Those are not the status icons, I saw some more, but they are in the same folder that WiFi status and there is an issue with that.

**Comment by germanfr** [comment]
Someone who has a Bluetooth device can test these? They must appear somewhere in the Bluetooth manager I guess.

**Comment by crutchcorn** [comment]
This must be closed due to the new changes in the repo. I will take the SVG and upload them for you  to the icons repo, and then upload the PNGs to this repo

**Pull request closed without merging**
