### PR TITLE
Add revamped shutdown pngs

### PR DESCRIPTION
**Pull request by germanfr**
I alredy uploaded the svg to the main repo.

### CODE REVIEW

**Comment by deadbaed** [comment]
what's the difference between the dirf?

**Comment by germanfr** [comment]
It now uses the Google icon. I already uploaded the svg to the main repo. These are just the pngs.

**Comment by deadbaed** [comment]
oh okay :)
I'll still wait to get corbin's confirmation, cause he's the boss :)

**Comment by germanfr** [comment]
Lol thank you

**Comment by crutchcorn** [comment]
ARG, THIS BE FINE ME HARTIES

**Comment by adueppen** [comment]
@crutchcorn International Talk Like a Pirate Day was September 19th. I think you missed it.

**Pull request merged**
